# pubspec.yaml

name: stock_market_app
description: A cross-platform Flutter app for tracking stocks.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.10.0"


dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.0.6

  easy_localization: ^3.0.1

  shared_preferences: ^2.0.15

  geolocator: ^9.0.2
  geocoding: ^2.0.1

  flutter_localizations:
    sdk: flutter

  # State management
  hooks_riverpod: ^2.0.0


  # Networking
  dio: ^5.0.0
  pretty_dio_logger: ^1.2.0

  # JSON serialization & data classes (compatible versions)
  freezed_annotation: ^2.0.0
  json_annotation: ^4.7.0

  # Charts
  fl_chart: ^0.70.1

  # Fonts
  google_fonts: ^4.0.3

  # Local persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  # Routing
  go_router: ^7.0.0

  # Firebase (optional â€“ remove if unused)
  firebase_core: ^2.6.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.4.0

  # Utilities
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.3.0
  freezed: ^2.0.0
  json_serializable: ^6.1.4
  hive_generator: ^2.0.1

  intl_utils: ^2.8.0
  flutter_launcher_icons: ^0.14.0    # supports image:^4.x
  flutter_native_splash:   ^2.3.1    # adds its own namespace for AGP 7+

dependency_overrides:
  logging: ^1.2.2


flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_class: AppLocalizations
  output_dir: lib/l10n
  template_arbs:
    - app_en.arb

flutter:
  generate: true
  uses-material-design: true

  # If you have image/icon assets, list them here:
  assets:
    - assets/images/tradion_dark.png
    - assets/images/tradion_light.png
    - assets/images/english.png
    - assets/images/spanish.png
    - assets/images/german.png
    - assets/images/russian.png
    - assets/images/turkish.png
    - assets/images/en.png
    - assets/images/es.png
    - assets/images/de.png
    - assets/images/ru.png
    - assets/images/tr.png
    - assets/translations/en.json
    - assets/translations/de.json
    - assets/translations/es.json
    - assets/translations/ru.json
    - assets/translations/tr.json
    - assets/icons/placeholder.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/tradion.png"
  adaptive_icon_foreground: "assets/images/tradion.png"
  adaptive_icon_background: "#10095A"

flutter_native_splash:
  color: "#10095A"               # background fill color while splash shows
  image: assets/images/tradion.png
  android: true
  ios: true
  android_disable_fullscreen: true

  android_12:
    image: assets/images/tradion.png
    icon_background_color: "#10095A"


  # If you bundle custom fonts (e.g. Inter), configure here:
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700
